# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1617badd8cd6c70014f9ffa4dfed7b82bb3b028d83e53e2a11837da2bad32cbce91abff4ce5470d6c7eb8a2572776fe18b6c72ce623a3f8d018e1eca486dbf94

test:
  secret_key_base: 59aa55fbc4e8ffaa9ede7c2d7ecd0647f93fae17063e3142f9dfb4a0471fc0a53d1a37eba6c182db0e74d7c16a4fe27c37bef889aedfb82a7e6537a9f70a4fb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
